name: print-hello-world
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]
jobs:
  echoing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello World!"

  using-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.my_secret }}
        run: |
          echo "Haha you no see: $SUPER_SECRET"

  sonar-cube-setup:
    runs-on: ubuntu-latest
    steps:
      - name: get files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  gradle-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 20.0.2
      - name: setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: execute gradle build
        run: ./gradlew build
