name: print-hello-world
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]
jobs:
  echoing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello World!"

  using-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.my_secret }}
        run: |
          echo "Haha you no see: $SUPER_SECRET"